# Generated by Django 4.1.2 on 2022-10-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=11)),
                ('codigo', models.CharField(max_length=8)),
                ('prod_entregar', models.IntegerField()),
                ('prod_falha', models.IntegerField()),
                ('prod_em_curso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=8)),
                ('endereco_entrega', models.TextField(max_length=250)),
                ('proprietario', models.CharField(max_length=100)),
                ('celular1', models.CharField(max_length=11)),
                ('celular2', models.CharField(max_length=11)),
                ('localizacao', models.CharField(max_length=30)),
            ],
        ),
    ]
